.TH rolldice 6
.SH NAME
.B rolldice
\- rolls virtual dice
.SH SYNOPSIS
.BR rolldice
.RB [ -s ]
.RI [ "dice string" ...]
.SH DESCRIPTION
.B rolldice
rolls virtual dice.
The dice strings passed on the command line contain information on the dice to roll in a format comparable to the format used in most role playing games.
.PP
If no dice string is provided as command line arguments,
.B rolldice
uses stdin as input and runs interactivelly.
.PP
The options are as follows:
.TP
.B -s
Print out the result of each individual die separately,
as well as the operations and totals.
.SS Dice string format
The dice string uses the exact format outlined below.
Optional parts are between square brackets.
A
.I #
must be replaced by a number.
.IP
.EX
.RI [ # x][ # ]d[ # |%][* # ][+ # |- # ][s # ]
.EE
.TP
.RI [ # x]
How many times to roll.
If omitted, defaults to 1 roll.
.TP
.RI [ # ]d[ # |%]
Main part of the dice string.
The first number is the number of dice to roll in each roll, if omitted, roll just one die.
The second number is the number of sides the dice have, if omitted, roll 6-sided die.
The second number can be replaced by a percent sign, implying a 100-sided die.
The numbers rolled on each die are then added up and given as the result.
.TP
.RI [* # ]
How many times to multiply the result of each roll.
If omitted, defaults to 1.
.TP
.RI [+ # |- # ]
Number to be added or subtracted, depending on the sign, from each roll.
If omitted, defaults to 0.
This step is handled after the multiplication.
.TP
.RI [s # ]
How many lowest dice rolls to drop.
If omitted, defaults to 0.
This step is handled before the multiplication.
.SH EXIT STATUS
.TP
.B 0
Success.
.TP
.B >0
Error occurred.
.SH EXAMPLES
Roll three six-sided dice and sum the results:
.IP
.EX
rolldice 3d
.EE
.PP
Roll four eight-sided dice and sum the results, them multiply the result by 2 and add 2 to it:
.IP
.EX
rolldice 4d8*2+2
.EE
.PP
Roll four six-sided dice, drop the lowest result and add the remaining results. Do this three times:
.IP
.EX
rolldice 3x4d6s1
.EE
.PP
.SH HISTORY
This version of
.B rolldice
was written as an exercise for practicing C.
.PP
This version of 
.B rolldice
was inspired (but not based) on the
.B rolldice
implementation by Stevie Strickland, but the code was written from scratch.
This manual, however, was based on the manual of Stevie's implementation.
